apiVersion: v1
kind: Service
metadata:
  name: webapp1-loadbalancer2-svc
  labels:
    app: webapp1-loadbalancer2
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: webapp1-loadbalancer2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp1-loadbalancer2-deployment
  labels:
    app: webapp1-loadbalancer2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp1-loadbalancer2
  template:
    metadata:
      labels:
        app: webapp1-loadbalancer2
    spec:
      containers:
      - name: webapp1-loadbalancer2-pod
        image: katacoda/docker-http-server:latest
        ports:
        - containerPort: 80
---
